apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-custom-resource-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
