{{ if .Values.clusterIngressDomain }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "quarkus-microservice.instance" . }}
  labels:
{{ include "quarkus-microservice.labels" . | indent 4 }}
spec:
  host: {{ include "quarkus-microservice.route-host" . }}
  path: /echo
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
  to:
    kind: Service
    name: {{ include "quarkus-microservice.instance" . }}
{{ end }}