apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-microservice.b-name" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.microservice.name }}
    app.kubernetes.io/instance: b
{{ include "quarkus-microservice.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.microservice.name }}
    app.kubernetes.io/instance: b
