apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-microservice.instance" . }}
  labels:
{{ include "quarkus-microservice.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
{{ include "quarkus-microservice.selectorLabels" . | indent 4 }}
