apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: academic-calendar
  name: academic-calendar
  namespace: academic-calendar-v2
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: /q/metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: academic-calendar
