apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-microservice.canary-name" . }}
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: canary
{{ include "quarkus-microservice.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: canary
