apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: /q/metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
