kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nshield-kneti
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nshield-license
  storageClassName: ''
  volumeMode: Filesystem
